#Auto-incremented patch version
#Tue Aug 18 22:49:20 UTC 2026
app.version.major=9
app.build.date=2026-08-18
app.version.patch=17
app.release.notes.url=https\://github.com/risa-labs-inc/BossConsole-Releases/releases/tag/v8.9.0
app.version.minor=4
app.release.channel=stable
app.version=9.4.17
app.build.number=1
app.prerelease.suffix=
